# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: MIT

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
        build_type:
          - Debug
          - Release
        qt:
          - version: "5.15.2"
            requested: "5.15"
            architectures: "x86_64"
          - version: "6.4.*"
            requested: "6.4"
            architectures: "x86_64;arm64"

    steps:
      - name: Install Qt with options and default aqtversion
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: null # use whatever the default is
          modules: ${{ matrix.qt.modules }}
          version: ${{ matrix.qt.requested }}
          cache: true

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        uses: turtlesec-no/get-ninja@main

      - name: Configure project
        run: >
          cmake -S . -B ./build -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_OSX_ARCHITECTURES="${{ matrix.qt.architectures }}"

      - name: Build Project
        run: cmake --build ./build
